In [1]:
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image
import numpy as np

def pprint(arr):
    print('type : {}'.format(type(arr)))
    print('shape : {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr)

numpy 입출력

In [2]:
# 깃헙

In [3]:
# 데모 배열 객체 생성
a = np.random.randint(0, 10, (2, 3))
pprint(a)
b = np.random.randint(0, 10, (2, 3))
pprint(b)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[5 1 0]
 [7 6 9]]
type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[9 8 5]
 [4 3 8]]


In [4]:
# 배열 객체 저장 - 바이너리 파일
# np.save(), np.savez() 메소드를 이용해서 배열 객체를 바이너리(2진) 형태의 파일로 저장할 수 있다.
# np.save() : 배열 1개를 저장한다. 확장자 => npy
# np.savez() : 배열 여러개를 저장한다. 확장자 => npz

# a 배열을 파일로 저장한다.
np.save('./output/my_array1', a)
# a, b 배열을 파일로 저장한다.
np.savez('./output/my_array1', a, b)

In [5]:
# np.load() 메소드로 npy, npz 파일로부터 배열 데이터를 읽어올 수 있다.
# npy 파일 읽기
print(np.load('./output/my_array1.npy'))
# npz 파일 읽기
print(np.load('./output/my_array1.npz')) # <numpy.lib.npyio.NpzFile object at 0x0000028CDBA9D148>
npzfiles = np.load('./output/my_array1.npz')
print(npzfiles['arr_0']) # arr_X sms 정해져 있는 값이므로 바꿀 수 없다.
print(npzfiles['arr_1'])

[[5 1 0]
 [7 6 9]]
[[5 1 0]
 [7 6 9]]
[[9 8 5]
 [4 3 8]]


In [6]:
# 데모 배열 객체 생성
data = np.random.random((3, 4))
pprint(data)

type : <class 'numpy.ndarray'>
shape : (3, 4), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0.43465406 0.58477396 0.98023032 0.98033512]
 [0.46570529 0.68439018 0.74536765 0.91524355]
 [0.75637263 0.03433825 0.56914492 0.78141745]]


In [7]:
# 배열 객체 저장 - 텍스트 파일
# np.savetxt() 메소드로 배열 객체를 텍스트 파일로 저장시킬 수 있다.
# np.savetxt('파일명', 데이터, delimiter='구분자')

# data 배열을 텍스트 파일로 저장한다.
np.savetxt('./output/saved.csv', data, delimiter=',')

In [8]:
# np.loadtxt() 메소드로 텍스트 파일로부터 배얄 객체를 읽어올 수 있다.
# np.loadtxt('파일명', dtype, delimiter='구분자')
print(np.loadtxt('./output/saved.csv', dtype=float, delimiter=',')) # 구분자는 데이터를 끊어 읽을 때 필요

[[0.43465406 0.58477396 0.98023032 0.98033512]
 [0.46570529 0.68439018 0.74536765 0.91524355]
 [0.75637263 0.03433825 0.56914492 0.78141745]]


배열(행렬) 연산 - 산술 연산

In [9]:
# 데모 배열 객체 생성

In [10]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)
b = np.arange(9, 0, -1).reshape(3, 3)
pprint(b)

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [11]:
# 덧셈 : +, np.add()
pprint(a + b)
pprint(np.add(a, b))

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [12]:
# 뺄셈 : -, np.subtract()
pprint(a - b)
pprint(np.subtract(a, b))

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [13]:
# 곱셈 : *, np.multiply()
pprint(a * b)
pprint(np.multiply(a, b))

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [14]:
# 나눗셈 : /, np.divide()
pprint(a / b)
pprint(np.divide(a, b))

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [15]:
pprint(np.exp(a)) # 지수함수

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [16]:
pprint(np.sqrt(a)) # 제곱근

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [17]:
# 삼각함수
pprint(np.sin(a))
pprint(np.cos(a))
pprint(np.tan(a))

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [18]:
pprint(np.log(a)) # 로그함수

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [19]:
pprint(np.dot(a, b)) # 행렬의 내적

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


비교 연산

In [20]:
# 배열의 요소별 비교 : >, >=, <, <=, ==, !=
print(a == b)

[[False False False]
 [False  True False]
 [False False False]]


In [21]:
# np.array_equal() 메소드를 사용하면 배열 전체를 비교할 수 있다.
print(np.array_equal(a, b))

False


집계 메소드

In [22]:
# numpy의 모든 집계 메소드는 axis를 기준으로 계산된다.
# 집계 apthemdp axis를 지정하지 않으면 axis = None이 기본값으로 사용된다. axis = None, axis = 0, axis = 1과같이 지정한다.

In [23]:
# 데모 배열 객체 생성
a = np.arange(1, 10).reshape(3, 3)
pprint(a)

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


합계 : 배열객체.sum(), np.sum(배열객체)

In [24]:
# axis = None
# axis = None은 전체 행렬을 하나의 배열로 간주하고 집계 함수의 범위를 전체 행렬로 정의한다. 생략시 기본값으로 사용된다.
# Image

In [25]:
print(a.sum())
print(np.sum(a))
print(a.sum(axis=None))
print(np.sum(a, axis=None))

45
45
45
45


In [26]:
# axis = 0
# axis = 0은 행을 기준으로 각 행의 동일한 인덱스 요소를 그룹으로 연산한다.
# Image

In [27]:
print(a.sum(axis=0))
print(np.sum(a, axis=0))

[12 15 18]
[12 15 18]


In [28]:
# axis = 1
# axis = 1은 열을 기준으로 각 열의 동일한 인덱스 요소를 그룹으로 연산한다.
# Image

In [29]:
print(a.sum(axis=1))
print(np.sum(a, axis=1))

[ 6 15 24]
[ 6 15 24]


최대값 : 배열객체.max(), np.max(배열객체), 최소값: 배열객체.min(), np.min(배열객체)

In [30]:
print(a.max())
print(np.max(a))
print(a.min())
print(np.min(a))

9
9
1
1


In [31]:
print(a.max(axis=0))
print(np.max(a, axis=0))
print(a.min(axis=0))
print(np.min(a, axis=0))

[7 8 9]
[7 8 9]
[1 2 3]
[1 2 3]


In [32]:
print(a.max(axis=1))
print(np.max(a, axis=1))
print(a.min(axis=1))
print(np.min(a, axis=1))

[3 6 9]
[3 6 9]
[1 4 7]
[1 4 7]


누적 합계 : 배열객체.cumsum(), np.cumsum(배열객체)

In [33]:
print(a.cumsum())
print(np.cumsum(a))

[ 1  3  6 10 15 21 28 36 45]
[ 1  3  6 10 15 21 28 36 45]


In [34]:
print(a.cumsum(axis=0))
print(np.cumsum(a, axis=0))

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [35]:
print(a.cumsum(axis=1))
print(np.cumsum(a, axis=1))

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


평균 : 배열객체.mean(), np.mean(배열객체)

In [36]:
print(a.mean())
print(np.mean(a))

5.0
5.0


In [37]:
print(a.mean(axis=0))
print(np.mean(a, axis=0))

[4. 5. 6.]
[4. 5. 6.]


In [38]:
print(a.mean(axis=1))
print(np.mean(a, axis=1))

[2. 5. 8.]
[2. 5. 8.]


중위수 : np.median(배열객체)

In [39]:
print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


상관계수 : np.corrcoef(배열객체)

In [40]:
print(np.corrcoef(a)) # axis를 사용하지 않는다.

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


표준편차 : 배열객체.std(), np.std(배열객체)

In [41]:
print(a.std())
print(np.std(a))

2.581988897471611
2.581988897471611


In [42]:
print(a.std(axis=0))
print(np.std(a, axis=0))

[2.44948974 2.44948974 2.44948974]
[2.44948974 2.44948974 2.44948974]


In [43]:
print(a.std(axis=1))
print(np.std(a, axis=1))

[0.81649658 0.81649658 0.81649658]
[0.81649658 0.81649658 0.81649658]


브로드캐스팅

In [44]:
# shape이 같은 두 배열에 대한 이항 연산은 배열 요소별로 실행된다.
# 두 배열의 shape이 다를 경우 두 배열 간의 형상을 맞추는 그림과 같은 브로드 캐스팅 과정을 거쳐서 실행된다.
# Image

shape이 같은 두 배열의 연산

In [45]:
a = np.arange(1, 25).reshape(4, 6)
pprint(a)
b = np.arange(25, 49).reshape(4, 6)
pprint(b)
# shape이 같은 두 배열을 이항 연산할 경우 위치가 같은 요소 단위로 실행된다.
pprint(a + b)

type : <class 'numpy.ndarray'>
shape : (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
type : <class 'numpy.ndarray'>
shape : (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]
type : <class 'numpy.ndarray'>
shape : (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[26 28 30 32 34 36]
 [38 40 42 44 46 48]
 [50 52 54 56 58 60]
 [62 64 66 68 70 72]]


shape이 다른 두 배열의 연산  
shape이 다른 두 배열 사이의 이항 연산에서 브로드캐스팅 발생 시 두 배열을 같은 shape으로 만든 후 연산을 실행한다.

In [46]:
# case 1 : 배열과 스칼라(단일 값)의 연산
# 배열과 스칼라 사이의 이항 연산 시 스칼라를 배열로 변환한다.
a = np.arange(1, 25).reshape(4, 6)
pprint(a)
pprint(a + 100)

type : <class 'numpy.ndarray'>
shape : (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
type : <class 'numpy.ndarray'>
shape : (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [47]:
# a + 100은 다음과 같은 과정을 거쳐서 처리된다.
new_arr = np.full_like(a, 100)
pprint(new_arr)
pprint(a + new_arr)

type : <class 'numpy.ndarray'>
shape : (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
type : <class 'numpy.ndarray'>
shape : (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [48]:
# case 2 : shape이 다른 배열의 연산
a = np.arange(5).reshape(1, 5)
pprint(a)
b = np.arange(5).reshape(5, 1)
pprint(b)
pprint(a + b)

type : <class 'numpy.ndarray'>
shape : (1, 5), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[0 1 2 3 4]]
type : <class 'numpy.ndarray'>
shape : (5, 1), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[0]
 [1]
 [2]
 [3]
 [4]]
type : <class 'numpy.ndarray'>
shape : (5, 5), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


벡터 연산

In [49]:
# numpy는 벡터 연산을 지원한다.
# numpy의 집합 연산에는 벡터화 기능이 적용되어 있어서 배열 처리에 대해 벡터 연산을 적용할 경우 처리 속도가 100배 이상 빠르다.
# 머신러닝에서 선형대수 연산을 처리할 때 매우 높은 효과를 낼 수 있다.
a = np.arange(10000000, dtype=np.int64)

In [52]:
%%time
result = 0
for i in a:
    result += i
print(result)

49999995000000
Wall time: 7.9 s


In [53]:
%%time
result = np.sum(a)
print(result)

49999995000000
Wall time: 18 ms


In [50]:
# ndarray 배열 객체에 대한 indexing, slice, subset이 반환하는 배열 새로운 객체가 아닌 기존 배열의 view이다.
# 반환된 배열의 값을 변경하면 원본 배열에 변경한 내용이 반영된다.
# 따라서, 기존 배열로부터 새로은 배열을 생성하기 copy() 메소드로 명시적으로 사용해야 한다.
# copy() 메소드로 복사된 배열은 원본 배열과 완전히 다른 별도의 객체가 된다.

In [55]:
a = np.random.randint(0, 9, (3, 3))
pprint(a)
a[:, 0] = 999 # a 배열의 모든 행의 0번 째 열을 999로 변경한다.
pprint(a)

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[5 3 0]
 [3 8 7]
 [6 3 4]]
type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[999   3   0]
 [999   8   7]
 [999   3   4]]


In [58]:
copied_a = np.copy(a)
pprint(copied_a)
copied_a[:, 1] = 777
pprint(copied_a)
pprint(a)

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[999   3   0]
 [999   8   7]
 [999   3   4]]
type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[999 777   0]
 [999 777   7]
 [999 777   4]]
type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[999   3   0]
 [999   8   7]
 [999   3   4]]


배열 정렬

In [65]:
# ndarray 객체는 axis를 기준으로 요소를 정렬하는 sort() 메소드를 제공한다.
# 원본 배열
unsorted_arr = np.random.random((3, 3))
print(unsorted_arr)

[[0.88437317 0.52300284 0.83184611]
 [0.37793754 0.03701575 0.85575231]
 [0.29412872 0.1647148  0.66361751]]


In [73]:
# sort 작업을 위해 원본을 복사한다.
unsorted_arr1 = unsorted_arr.copy()
unsorted_arr2 = unsorted_arr.copy()
unsorted_arr3 = unsorted_arr.copy()

In [74]:
# 배열객체.sort()
# sort() 메소드 axis의 기본값은 None이 아니고 -1이다.
# -1은 현재 배열의 마지막 axis를 의미하고 unsorted_arr의 마지막 axis는 1이다.
# 배열객체.sort()와 배열객체.sort(axis = 1)의 결과는 같다.

In [75]:
unsorted_arr1.sort()
pprint(unsorted_arr1)

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0.52300284 0.83184611 0.88437317]
 [0.03701575 0.37793754 0.85575231]
 [0.1647148  0.29412872 0.66361751]]


In [76]:
unsorted_arr2.sort(axis = 0)
pprint(unsorted_arr2)

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0.29412872 0.03701575 0.66361751]
 [0.37793754 0.1647148  0.83184611]
 [0.88437317 0.52300284 0.85575231]]


In [81]:
unsorted_arr2.sort(axis = 1)
pprint(unsorted_arr2)

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0.03701575 0.29412872 0.66361751]
 [0.1647148  0.37793754 0.83184611]
 [0.52300284 0.85575231 0.88437317]]
